// Code generated by ogen, DO NOT EDIT.

package client

import (
	"fmt"

	"github.com/go-faster/errors"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/AuthUser
type AuthUser struct {
	ID    int64        `json:"id"`
	Name  string       `json:"name"`
	Email string       `json:"email"`
	Role  AuthUserRole `json:"role"`
}

// GetID returns the value of ID.
func (s *AuthUser) GetID() int64 {
	return s.ID
}

// GetName returns the value of Name.
func (s *AuthUser) GetName() string {
	return s.Name
}

// GetEmail returns the value of Email.
func (s *AuthUser) GetEmail() string {
	return s.Email
}

// GetRole returns the value of Role.
func (s *AuthUser) GetRole() AuthUserRole {
	return s.Role
}

// SetID sets the value of ID.
func (s *AuthUser) SetID(val int64) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *AuthUser) SetName(val string) {
	s.Name = val
}

// SetEmail sets the value of Email.
func (s *AuthUser) SetEmail(val string) {
	s.Email = val
}

// SetRole sets the value of Role.
func (s *AuthUser) SetRole(val AuthUserRole) {
	s.Role = val
}

func (*AuthUser) loginUserRes()    {}
func (*AuthUser) registerUserRes() {}

type AuthUserRole string

const (
	AuthUserRoleAdmin    AuthUserRole = "admin"
	AuthUserRoleCustomer AuthUserRole = "customer"
)

// AllValues returns all AuthUserRole values.
func (AuthUserRole) AllValues() []AuthUserRole {
	return []AuthUserRole{
		AuthUserRoleAdmin,
		AuthUserRoleCustomer,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s AuthUserRole) MarshalText() ([]byte, error) {
	switch s {
	case AuthUserRoleAdmin:
		return []byte(s), nil
	case AuthUserRoleCustomer:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *AuthUserRole) UnmarshalText(data []byte) error {
	switch AuthUserRole(data) {
	case AuthUserRoleAdmin:
		*s = AuthUserRoleAdmin
		return nil
	case AuthUserRoleCustomer:
		*s = AuthUserRoleCustomer
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type CookieAuth struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *CookieAuth) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *CookieAuth) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *CookieAuth) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *CookieAuth) SetRoles(val []string) {
	s.Roles = val
}

// DeletePetNoContent is response for DeletePet operation.
type DeletePetNoContent struct{}

// Ref: #/components/schemas/Error
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() int32 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val int32) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

func (*Error) loginUserRes()    {}
func (*Error) registerUserRes() {}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// Ref: #/components/schemas/LoginRequest
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// GetEmail returns the value of Email.
func (s *LoginRequest) GetEmail() string {
	return s.Email
}

// GetPassword returns the value of Password.
func (s *LoginRequest) GetPassword() string {
	return s.Password
}

// SetEmail sets the value of Email.
func (s *LoginRequest) SetEmail(val string) {
	s.Email = val
}

// SetPassword sets the value of Password.
func (s *LoginRequest) SetPassword(val string) {
	s.Password = val
}

// LogoutUserNoContent is response for LogoutUser operation.
type LogoutUserNoContent struct{}

// Ref: #/components/schemas/NewPet
type NewPet struct {
	Name string    `json:"name"`
	Tag  OptString `json:"tag"`
}

// GetName returns the value of Name.
func (s *NewPet) GetName() string {
	return s.Name
}

// GetTag returns the value of Tag.
func (s *NewPet) GetTag() OptString {
	return s.Tag
}

// SetName sets the value of Name.
func (s *NewPet) SetName(val string) {
	s.Name = val
}

// SetTag sets the value of Tag.
func (s *NewPet) SetTag(val OptString) {
	s.Tag = val
}

// NewOptInt32 returns new OptInt32 with value set to v.
func NewOptInt32(v int32) OptInt32 {
	return OptInt32{
		Value: v,
		Set:   true,
	}
}

// OptInt32 is optional int32.
type OptInt32 struct {
	Value int32
	Set   bool
}

// IsSet returns true if OptInt32 was set.
func (o OptInt32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt32) Reset() {
	var v int32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt32) SetTo(v int32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt32) Get() (v int32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt32) Or(d int32) int32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Merged schema.
// Ref: #/components/schemas/Pet
type Pet struct {
	Name string    `json:"name"`
	Tag  OptString `json:"tag"`
	ID   int64     `json:"id"`
}

// GetName returns the value of Name.
func (s *Pet) GetName() string {
	return s.Name
}

// GetTag returns the value of Tag.
func (s *Pet) GetTag() OptString {
	return s.Tag
}

// GetID returns the value of ID.
func (s *Pet) GetID() int64 {
	return s.ID
}

// SetName sets the value of Name.
func (s *Pet) SetName(val string) {
	s.Name = val
}

// SetTag sets the value of Tag.
func (s *Pet) SetTag(val OptString) {
	s.Tag = val
}

// SetID sets the value of ID.
func (s *Pet) SetID(val int64) {
	s.ID = val
}

// Ref: #/components/schemas/RegisterRequest
type RegisterRequest struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

// GetName returns the value of Name.
func (s *RegisterRequest) GetName() string {
	return s.Name
}

// GetEmail returns the value of Email.
func (s *RegisterRequest) GetEmail() string {
	return s.Email
}

// GetPassword returns the value of Password.
func (s *RegisterRequest) GetPassword() string {
	return s.Password
}

// SetName sets the value of Name.
func (s *RegisterRequest) SetName(val string) {
	s.Name = val
}

// SetEmail sets the value of Email.
func (s *RegisterRequest) SetEmail(val string) {
	s.Email = val
}

// SetPassword sets the value of Password.
func (s *RegisterRequest) SetPassword(val string) {
	s.Password = val
}
