// Code generated by ogen, DO NOT EDIT.

package client

// DeletePetParams is parameters of deletePet operation.
type DeletePetParams struct {
	// ID of pet to delete.
	ID int64
}

// FindPetByIDParams is parameters of find pet by id operation.
type FindPetByIDParams struct {
	// ID of pet to fetch.
	ID int64
}

// FindPetsParams is parameters of findPets operation.
type FindPetsParams struct {
	// Tags to filter by.
	Tags []string `json:",omitempty"`
	// Maximum number of results to return.
	Limit OptInt32 `json:",omitempty,omitzero"`
}
