// Code generated by ogen, DO NOT EDIT.

package client

// OperationName is the ogen operation name
type OperationName = string

const (
	AddPetOperation         OperationName = "AddPet"
	DeletePetOperation      OperationName = "DeletePet"
	FindPetByIDOperation    OperationName = "FindPetByID"
	FindPetsOperation       OperationName = "FindPets"
	GetCurrentUserOperation OperationName = "GetCurrentUser"
	LoginUserOperation      OperationName = "LoginUser"
	LogoutUserOperation     OperationName = "LogoutUser"
	RegisterUserOperation   OperationName = "RegisterUser"
)
