// Code generated by ogen, DO NOT EDIT.

package client

import (
	"context"
	"net/http"

	"github.com/go-faster/errors"
)

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// CookieAuth provides cookieAuth security value.
	// JWT access token in an HttpOnly cookie.
	CookieAuth(ctx context.Context, operationName OperationName) (CookieAuth, error)
}

func (s *Client) securityCookieAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.CookieAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"CookieAuth\"")
	}
	req.AddCookie(&http.Cookie{
		Name:  "access_token",
		Value: t.APIKey,
	})
	return nil
}
